name = "spectrelink-entry"
main = "src/workers/entry-worker.js" # Adjusted path
compatibility_date = "2024-03-01" # General recent date
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
EXIT_WORKER_URL = "https://spectrelink-exit.your-account.workers.dev" # Placeholder - user must change
HTTP_NEXT_HOP_URL = "https://spectrelink-exit.your-account.workers.dev" # Placeholder - user must change

# The SHARED_KEY secret must be configured via:
# wrangler secret put SHARED_KEY --name spectrelink-entry --env production
# Use a 64-character hex string (32 bytes)

[[services]]
binding = "EXIT_SERVICE" # This is how entry-worker.js refers to the exit worker service
service = "spectrelink-exit" # The *name* of your deployed exit worker service
environment = "production"
